### ISSUE TITLE
Requires directly adding `Test` as a dependency.

### ISSUE THREAD

**Issue by JamieMair** [julia-vscode/TestItemRunner.jl#35]
Requires having `Test` as a direct dependency of the project, instead of being part of the `[extras]` dependency. E.g. it would be nice to work when the `Project.toml` file looks like:
```toml
name = "MyPackage"
uuid = "some-uuid"
authors = ["author and contributers"]
version = "0.1.0"

[deps]
OtherPackage = "some-uuid"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[targets]
test = ["Test", "TestItemRunner", "TestItems"]
```
Without having to list `Test` under the `[deps]` section.
